[project]
name = "hacker-news-ja-summary-rss"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llm-gemini>=0.17",
    "llm-hacker-news>=0.1",
    "markdown>=3.8",
]
